### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by jondo** [kozakja4/thesis#1]
Hello @kozakja4, I would like to reproduce your work. For doing this lawfully, I need to have a license, as described [here](https://help.github.com/articles/licensing-a-repository/). Can you please [choose an Open Source license](https://choosealicense.com/) and  [add it to the repository](https://help.github.com/articles/adding-a-license-to-a-repository/)?

**Comment by kozakja4** [comment]
Hello,

I added MIT license, so you should be free to use the code in any way you need.
